//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
var ver='4.0.1'
var m5=new Object
m5.name='m5'
m5.fnm='menu_m5'
if(!window.lastm||window.lastm<5)lastm=5
m5.v17=null
m5.v17Timeout=''
var maxZ=1000
m5.v18
m5.targetFrame
var docLoaded=false
m5.bIncBorder=true
m5.v29=null
m5.v29Str=''
m5.v55=50
m5.scrollStep=10
m5.fadingSteps=8
m5.itemOverDelay=0
m5.transTLO=0
m5.fixSB=0
m5.v62=0
var pth=document.getElementById('TrackPath_m5').src
if(pth.lastIndexOf("\\")>pth.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
var pths=pth.lastIndexOf(sepCh)
pth=(pths==-1)?'.':pth.substring(0,pths)
m5.v21=pth
pths=pth.lastIndexOf(sepCh)
pth=(pths==-1)?'.':pth.substring(0,pths)
m5.v57=pth
m5.v56="<root>"
m5.maxlev=0
m5.v22=0
m5.sepH=10
m5.bHlNL=1
m5.showA=1
m5.bVarWidth=0
m5.bShowDel=0
m5.scrDel=0
m5.v23=150
m5.levelOffset=20
m5.bord=1
m5.vertSpace=5
m5.sep=1
m5.v19=false
m5.bkv=0
m5.rev=0
m5.shs=0
m5.xOff=0
m5.yOff=0
m5.xSOff=0
m5.ySOff=2
m5.v20=false
m5.cntFrame=""
m5.menuFrame=""
m5.v24=""
m5.mout=true
m5.iconSize=8
m5.closeDelay=1000
m5.tlmOrigBg="#cc0000"
m5.tlmOrigCol="White"
m5.v25=false
m5.v52=false
m5.v60=75
m5.v11=false
m5.v10=0
m5.ppLeftPad=5
m5.v54=0
m5.v01=2
m5.tlmHlBg="#F00000"
m5.tlmHlCol="Black"
m5.borderCol="white"
m5.menuHorizontal=true
m5.scrollHeight=6
m5.attr=new Array("11px",false,false,"Black","#B2CFEB","White","Arial,Helvetica","#003366","White","#cc0000")
absPath=""
if(m5.v19&&!m5.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m5.v02=m5.v23
document.write("<style type='text/css'>\n.m5CL0,.m5CL0:link{text-decoration:none;width:100%;color:White; }\n.m5CL0:visited{color:White}\n.m5mit{padding-left:15px;padding-right:15px;color:White; font-family:geneva,sans serif; font-size:12px; }\n"+"</"+"style>")
document.write("<script type='text/javascript' src='"+eval('window.m'+lastm).v21+"/menu_dom.js'></"+"script>")
