//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
var ver='4.0.1'
var m2=new Object
m2.name='m2'
m2.fnm='menu_m2'
if(!window.lastm||window.lastm<2)lastm=2
m2.v17=null
m2.v17Timeout=''
var maxZ=1000
m2.v18
m2.targetFrame
var docLoaded=false
m2.bIncBorder=true
m2.v29=null
m2.v29Str=''
m2.v55=50
m2.scrollStep=10
m2.fadingSteps=8
m2.itemOverDelay=0
m2.transTLO=0
m2.fixSB=0
m2.v62=0
var pth=document.getElementById('TrackPath_m2').src
if(pth.lastIndexOf("\\")>pth.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
var pths=pth.lastIndexOf(sepCh)
pth=(pths==-1)?'.':pth.substring(0,pths)
m2.v21=pth
pths=pth.lastIndexOf(sepCh)
pth=(pths==-1)?'.':pth.substring(0,pths)
m2.v57=pth
m2.v56="<root>"
m2.maxlev=0
m2.v22=0
m2.sepH=10
m2.bHlNL=1
m2.showA=1
m2.bVarWidth=0
m2.bShowDel=0
m2.scrDel=0
m2.v23=150
m2.levelOffset=20
m2.bord=1
m2.vertSpace=5
m2.sep=1
m2.v19=false
m2.bkv=0
m2.rev=0
m2.shs=0
m2.xOff=0
m2.yOff=0
m2.xSOff=0
m2.ySOff=2
m2.v20=false
m2.cntFrame=""
m2.menuFrame=""
m2.v24=""
m2.mout=true
m2.iconSize=8
m2.closeDelay=1000
m2.tlmOrigBg="#cc0000"
m2.tlmOrigCol="White"
m2.v25=false
m2.v52=false
m2.v60=75
m2.v11=false
m2.v10=0
m2.ppLeftPad=5
m2.v54=0
m2.v01=2
m2.tlmHlBg="#F00000"
m2.tlmHlCol="Black"
m2.borderCol="white"
m2.menuHorizontal=true
m2.scrollHeight=6
m2.attr=new Array("11px",false,false,"Black","#B2CFEB","White","Arial,Helvetica","#003366","White","#cc0000")
absPath=""
if(m2.v19&&!m2.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m2.v02=m2.v23
document.write("<style type='text/css'>\n.m2CL0,.m2CL0:link{text-decoration:none;width:100%;color:White; }\n.m2CL0:visited{color:White}\n.m2mit{padding-left:15px;padding-right:15px;color:White; font-family:aipainunavik; font-size:12px; }\n"+"</"+"style>")
document.write("<script type='text/javascript' src='"+eval('window.m'+lastm).v21+"/menu_dom.js'></"+"script>")
